// CyberEd — Materi Pertahanan Batch 1 (5 materi)
// Firewall/IDS, Network Segmentation, WAF, WiFi Security, Secure Coding
import type { MateriData } from '../materi-content/runner';

export const pertahanan1: MateriData[] = [
  // ============================ FIREWALL & IDS/IPS ============================
  {
    judul: '🔥 Firewall & IDS/IPS Configuration — Pertahanan Garis Depan Jaringan',
    emoji: '🔥',
    deskripsi: 'Pelajari cara setup firewall iptables + IDS Suricata di Linux. Termasuk rules block port scan, deteksi port scanning dengan Snort, dan lab lengkap.',
    level: 'menengah',
    harga: 20000,
    hargaCoret: 30000,
    isGratis: true,
    tipe: 'pertahanan',
    tujuan: 'Kamu paham konsep firewall stateful vs stateless, mampu setup iptables rules untuk block traffic berbahaya, dan bisa install + configure IDS Suricata untuk mendeteksi attack signature.',
    analogy: 'Bayangkan rumah Anda dijaga satpam. Satpam punya daftar nama tamu yang boleh masuk (allow list) dan nama yang tidak boleh masuk (block list). Firewall = satpam digital untuk jaringan komputer. IDS = satpam yang juga lihat gerak-gerik mencurigakan di dalam rumah.',
    apaItu: 'Firewall adalah sistem keamanan jaringan yang mengontrol lalu lintas berdasarkan sekumpulan rule. Ada 2 jenis utama:\n\n1) **Stateless** (Packet Filter): cek tiap paket independen. Tidak ingat koneksi sebelumnya.\n2) **Stateful** (Connection Tracking): ingat koneksi, cek apakah paket baru ini bagian dari koneksi yang dikenal.\n\nIDS (Intrusion Detection System): monitor traffic, deteksi pattern attack, ALERT saja.\nIPS (Intrusion Prevention System): IDS + otomatis BLOCK attack yang terdeteksi.',
    senjata: {
      pc: '**iptables** (built-in Linux), **nftables** (modern replacement), **UFW** (Ubuntu Friendly Firewall), **Suricata** (IDS/IPS modern), **Snort** (lama tapi reliable), **Wireshark** (analisis paket).',
      hp: 'HP Android dengan Termux — bisa install iptables + nftables. Tapi IDS full biasanya butuh dedicated hardware/server.',
    },
    metode: [
      {
        nama: 'Metode 1: Setup Firewall dengan UFW (Pemula)',
        level: 'pemula',
        deskripsi: 'UFW (Uncomplicated Firewall) adalah wrapper iptables yang lebih user-friendly. Cara paling cepat untuk pemula pemula setting firewall di Linux/Ubuntu.',
        prasyarat: [
          'Linux Ubuntu/Debian (UFW default terinstall)',
          'Hak sudo',
          'Backup rules lama: `sudo iptables-save > ~/iptables-backup.rules`',
        ],
        langkah: [
          {
            judul: 'Cek status UFW saat ini',
            aksi: 'Kalian buka terminal. Cek apakah UFW sudah jalan: `sudo ufw status verbose`. Output yang belum diaktifkan akan bilang `Status: inactive`. Kalau active, akan tampil daftar rules.',
            command: 'sudo ufw status verbose',
            expected: 'Status: inactive (kalau belum diaktifkan)',
          },
          {
            judul: 'Aktifkan UFW + default policy',
            aksi: 'Aktifkan: `sudo ufw enable`. UFW akan load default policy: deny incoming, allow outgoing. Artinya koneksi dari luar diblok default, tapi kamu boleh keluar. Ini rule aman default.\n\nAtau set policy secara manual: `sudo ufw default deny incoming && sudo ufw default allow outgoing && sudo ufw enable`.',
            command: 'sudo ufw enable',
            expected: 'Firewall is active and enabled on system startup',
          },
          {
            judul: 'Allow SSH supaya tidak terkunci',
            aksi: '⚠️ PENTING: kalau Anda setup remote server, jangan lupa allow SSH dulu sebelum enable. `sudo ufw allow 22/tcp` (atau custom port Anda). Kalau lupa dan terkunci dari SSH, perlu akses console langsung.',
            command: 'sudo ufw allow 22/tcp',
            expected: 'Rules updated. SSH allowed.',
          },
          {
            judul: 'Allow HTTP/HTTPS untuk web server',
            aksi: 'Kalau Anda host website, allow port 80/443: `sudo ufw allow 80/tcp && sudo ufw allow 443/tcp`. Atau spesifik service: `sudo ufw allow http && sudo ufw allow https`.',
            command: 'sudo ufw allow 80/tcp\nsudo ufw allow 443/tcp',
            expected: 'Rules updated.',
          },
          {
            judul: 'Block port tertentu (teleport SSH abuse)',
            aksi: 'Block specific port yang sering disalahgunakan: `sudo ufw deny 23/tcp` (telnet, insecure), `sudo ufw deny 3389/tcp` (RDP dari Windows, kalau server Linux tidak perlu), `sudo ufw deny from 203.0.113.0/24` (block subnet spesifik).',
            command: 'sudo ufw deny 23/tcp\nsudo ufw deny from 203.0.113.0/24',
            expected: 'Rules updated.',
          },
          {
            judul: 'Cek rules aktif',
            aksi: 'Cek rule aktif: `sudo ufw status numbered`. Akan muncul daftar semua rules dengan nomor urut. Setiap rule bisa dihapus pakai `sudo ufw delete <nomor>`.',
            command: 'sudo ufw status numbered',
            expected: 'Daftar rules dengan nomor urut.',
          },
        ],
        outputAkhir: 'Berhasil setup UFW firewall dengan rules dasar (allow SSH + web, deny protocol lama).',
        kesalahanUmum: [
          { masalah: '❌ Terkunci dari SSH setelah enable UFW', solusi: 'Pastikan `sudo ufw allow 22/tcp` sudah dijalankan SEBELUM enable. Kalau sudah kena, pakai akses console langsung.' },
          { masalah: '❌ Rules tidak apply', solusi: 'Cek: `sudo ufw status`. Kalau ada error, lihat `/var/log/ufw.log` untuk detail.' },
        ],
      },
      {
        nama: 'Metode 2: iptables Manual dengan Stateful Rules (Menengah)',
        level: 'menengah',
        deskripsi: 'Untuk kontrol yang lebih dalam, pakai iptables langsung. Stateful rules (NEW, ESTABLISHED, RELATED) sangat efektif untuk block SYN flood dan scan.',
        prasyarat: [
          'Linux',
          'Sudo access',
          'Backup iptables: `sudo iptables-save > ~/backup.rules`',
        ],
        langkah: [
          {
            judul: 'Cek rules iptables saat ini',
            aksi: 'Cek rules: `sudo iptables -L -v --line-numbers`. Akan muncul tabel INPUT, FORWARD, OUTPUT. Baris = rule. Kolom `policy` di atas = default policy (biasanya ACCEPT semua).',
            command: 'sudo iptables -L -v --line-numbers',
            expected: 'Rules saat ini.',
          },
          {
            judul: 'Set default policy ke drop',
            aksi: '⚠️ Atur policy ke DROP semua first (whitelist approach): `sudo iptables -P INPUT DROP && sudo iptables -P FORWARD DROP && sudo iptables -P OUTPUT ACCEPT`. Output ACCEPT karena kita perlu allow traffic keluar.\n\nSebelum ini, allow loopback dulu supaya service internal jalan: `sudo iptables -A INPUT -i lo -j ACCEPT`.',
            command: 'sudo iptables -P INPUT DROP\nsudo iptables -P FORWARD DROP\nsudo iptables -P OUTPUT ACCEPT\nsudo iptables -A INPUT -i lo -j ACCEPT',
            expected: 'Default policies set. Loopback allowed.',
          },
          {
            judul: 'Allow established + related connections',
            aksi: 'Tambahkan: `sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT`. Ini artinya: packet bagian dari koneksi yang valid (kamu sudah establish) AKAN otomatis di-allow. Sangat penting untuk response dari web server, dll.',
            command: 'sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT',
            expected: 'Established/related packets auto-allowed.',
          },
          {
            judul: 'Limit SYN untuk prevent SYN flood',
            aksi: 'Batasi SYN baru per detik: `sudo iptables -A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 3 -j ACCEPT`. Limit-burst 3 artinya burst 3 paket di-allow, lalu limit 1/detik. Di luar itu → DROP.',
            command: 'sudo iptables -A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 3 -j ACCEPT',
            expected: 'SYN flood protection enabled.',
          },
          {
            judul: 'Block ping (ICMP echo-request)',
            aksi: 'Untuk stealth server: `sudo iptables -A INPUT -p icmp --icmp-type echo-request -j DROP`. Server jadi tidak merespons ping = lebih invisible.',
            command: 'sudo iptables -A INPUT -p icmp --icmp-type echo-request -j DROP',
            expected: 'Ping DROP. Server stealth.',
          },
          {
            judul: 'Save rules untuk persistensi',
            aksi: 'iptables rules HILANG setelah reboot. Save untuk persist: install `iptables-persistent` (`sudo apt install iptables-persistent`). Cek current rules: `sudo iptables-save > /etc/iptables/rules.v4`.\n\nAtau runtime save: `sudo netfilter-persistent save` di Debian/Ubuntu.',
            command: 'sudo apt install iptables-persistent\nsudo netfilter-persistent save',
            expected: 'Rules persisted across reboot.',
          },
        ],
        outputAkhir: 'Berhasil setup iptables stateful rules + SYN limit + ICMP stealth. Rules persisten via iptables-persistent.',
        kesalahanUmum: [
          { masalah: '❌ Lost koneksi SSH setelah rules', solusi: 'Selalu allow SSH dulu (22/tcp) sebelum change policy. Atau pakai koneksi konsol langsung.' },
          { masalah: '❌ Rules tidak persisten', solusi: 'Install iptables-persistent dan save rules. Cek /etc/iptables/rules.v4 ada isinya.' },
        ],
      },
      {
        nama: 'Metode 3: Install + Setup Suricata IDS (Lanjut)',
        level: 'lanjut',
        deskripsi: 'Suricata adalah IDS/IPS modern paling powerful. Setup lengkap dengan rules ET Open untuk detect attack signature.',
        prasyarat: [
          'Linux (Ubuntu/Debian)',
          'Resource cukup (RAM 4GB+ untuk production)',
          'Interface jaringan dedicated untuk monitor',
        ],
        langkah: [
          {
            judul: 'Install Suricata',
            aksi: 'Kalian install: `sudo apt install software-properties-common -y && sudo add-apt-repository ppa:oisf/suricata-stable && sudo apt update && sudo apt install suricata -y`. PPA ini version stabil terbaru.',
            command: 'sudo apt install suricata -y',
            expected: 'Suricata installed.',
          },
          {
            judul: 'Cek interface di konfigurasi',
            aksi: 'Edit config: `sudo nano /etc/suricata/suricata.yaml`. Cari baris `af-packet` (default interface). Ganti dengan interface Anda (`eth0` / `enp0s3`). Untuk home network biasanya `eth0`.',
            expected: 'Configured interface.',
          },
          {
            judul: 'Download rules ET Open',
            aksi: 'Install tool rules: `sudo apt install suricata-update -y`. Update rules: `sudo suricata-update`. Rules akan tersimpan di `/var/lib/suricata/rules/`.',
            command: 'sudo suricata-update',
            expected: 'ET Open rules downloaded.',
          },
          {
            judul: 'Enable dan start Suricata',
            aksi: 'Aktifkan: `sudo systemctl enable suricata && sudo systemctl start suricata`. Cek: `sudo systemctl status suricata`. Seharusnya running.',
            command: 'sudo systemctl enable suricata\nsudo systemctl start suricata\nsudo systemctl status suricata',
            expected: 'Active: active (running).',
          },
          {
            judul: 'Tes detection dengan nmap dari PC kedua',
            aksi: 'Dari PC kedua, scan Suricata-host: `nmap -sS -p 1-1000 SURICATA_IP`. Cek log Suricata: `sudo tail -f /var/log/suricata/fast.log`. Seharusnya muncul alert: `[1:XXX:X] ALERT MESSAGE ...`.',
            command: 'nmap -sS -p 1-1000 SURICATA_IP\nsudo tail -f /var/log/suricata/fast.log',
            expected: 'Alert ET SCAN muncul di fast.log.',
          },
        ],
        outputAkhir: 'Berhasil install Suricata IDS. Detect nmap scan dari PC kedua. Rules ET Open aktif.',
        kesalahanUmum: [
          { masalah: '❌ Tidak ada alert saat nmap', solusi: 'Cek interface config di suricata.yaml. Cek juga mode IDS vs IPS — default IDS di suricata.yaml.' },
          { masalah: '❌ Suricata banyak CPU usage', solusi: 'Normal untuk traffic tinggi. Tune: `max-pending-packets: 65534` di config. Untuk production, butuh 8GB+ RAM dan multi-core.' },
        ],
      },
    ],
    mitigasi: 'Pertahanan tambahan firewall:\n\n**Default deny**: set policy ke DROP/REJECT untuk INPUT/FORWARD, hanya allow yang perlu.\n\n**Geo-blocking**: UFW + ipset atau implementasi nginx geoip module untuk block traffic dari region yang tidak relevan.\n\n**Rate limiting**: pakai iptables `recent` module atau mod_evasive di Apache untuk limit HTTP req per IP.\n\n**Monitoring log**: pasang fail2ban untuk auto-block IP yang gagal SSH berkali-kali.',
  } as MateriData,
  // ============================ NETWORK SEGMENTATION ============================
  {
    judul: '🏰 Network Segmentation & Hardening — Bagi Jaringan untuk Kurangi Risiko',
    emoji: '🏰',
    deskripsi: 'Pelajari cara setup VLAN di switch, segmentasi jaringan production/dev, dan hardening OS Linux dengan CIS Benchmarks.',
    level: 'menengah',
    harga: 18000,
    hargaCoret: 28000,
    isGratis: false,
    tipe: 'pertahanan',
    tujuan: 'Kamu paham konsep Zero Trust + defense in depth, mampu setup VLAN untuk memisahkan subnet (user/server/IoT), dan tahu teknologi microsegmentation modern.',
    analogy: 'Bayangkan kapal besar dengan banyak ruangan. Kalau satu bocor, air mengalir ke seluruh kapal. Tapi kalau ada sekat-sekat (compartment), satu ruangan bocor = aman, kapal masih bisa jalan. Network segmentation = buat sekat-sekat di jaringan supaya kalau satu kena attack, tidak langsung meluas ke seluruh organisasi.',
    apaItu: 'Network Segmentation adalah strategi membagi jaringan besar menjadi beberapa subnet/logical zone yang terisolasi. Tujuannya: kalau satu zone kena attack (compromised), attacker tidak bisa langsung pivot ke zone lain.\n\nJenis segmentasi:\n- **VLAN** (Layer 2): pisahkan broadcast domain\n- **Subnet** (Layer 3): pisahkan IP range dengan router\n- **Microsegmentation** (modern): tiap workload/application punya policy sendiri',
    senjata: { pc: 'Switch manageable (Cisco / Mikrotik / Ubiquiti), `iptables`/`nftables`, `firewalld`, Linux host network namespaces. Untuk lab tanpa hardware: GNS3 / EVE-NG / CML untuk virtual.', hp: 'Tidak relevan — segmentation butuh switch/router dedicated.' },
    metode: [
      {
        nama: 'Metode 1: Setup VLAN di Linux dengan ip command (Pemula)',
        level: 'pemula',
        deskripsi: 'Untuk home lab atau virtual switch, bisa setup VLAN via Linux tanpa hardware switch. Cara virtualisasi terbaik untuk pemula.',
        prasyarat: [
          'Linux dengan `iproute2` (semua distro modern)',
          'Sudo access',
          'Interface Ethernet utama (eth0)',
        ],
        langkah: [
          { judul: 'Cek interface & VLAN support', aksi: 'Cek apakah kernel support VLAN: `sudo modprobe 8021q`. Cek interface: `ip link show`. Anda akan lihat `eth0` — interface utama. VLAN akan jadi virtual di atasnya.', command: 'sudo modprobe 8021q\nip link show', expected: 'Interface eth0 muncul.' },
          { judul: 'Buat VLAN interface 10 (HR)', aksi: 'Buat VLAN 10 (mis: untuk tim HR): `sudo ip link add link eth0 name eth0.10 type vlan id 10`. Beri IP: `sudo ip addr add 192.168.10.1/24 dev eth0.10`. Aktifkan: `sudo ip link set eth0.10 up`.', command: 'sudo ip link add link eth0 name eth0.10 type vlan id 10\nsudo ip addr add 192.168.10.1/24 dev eth0.10\nsudo ip link set eth0.10 up', expected: 'VLAN 10 UP dengan IP 192.168.10.1/24.' },
          { judul: 'Buat VLAN 20 (Engineering) + VLAN 30 (Server)', aksi: 'VLAN 20 untuk Engineering: `sudo ip link add link eth0 name eth0.20 type vlan id 20 && sudo ip addr add 192.168.20.1/24 dev eth0.20 && sudo ip link set eth0.20 up`. VLAN 30 untuk Server: `sudo ip link add link eth0 name eth0.30 type vlan id 30 && sudo ip addr add 192.168.30.1/24 dev eth0.30 && sudo ip link set eth0.30 up`.', command: 'sudo ip link add link eth0 name eth0.20 type vlan id 20\nsudo ip addr add 192.168.20.1/24 dev eth0.20\nsudo ip link set eth0.20 up\nsudo ip link add link eth0 name eth0.30 type vlan id 30\nsudo ip addr add 192.168.30.1/24 dev eth0.30\nsudo ip link set eth0.30 up', expected: '3 VLANs up dengan subnet berbeda.' },
          { judul: 'Block lintas-VLAN dengan iptables', aksi: 'Network segmentation butuh blok traffic antar subnet non-permitted. Block Engineering→HR: `sudo iptables -A INPUT -s 192.168.20.0/24 -d 192.168.10.0/24 -j DROP`. Block HR→Server: `sudo iptables -A INPUT -s 192.168.10.0/24 -d 192.168.30.0/24 -j DROP`.', command: 'sudo iptables -A INPUT -s 192.168.20.0/24 -d 192.168.10.0/24 -j DROP\nsudo iptables -A INPUT -s 192.168.10.0/24 -d 192.168.30.0/24 -j DROP', expected: 'Traffic antar VLAN dibatasi.' },
        ],
        outputAkhir: 'Berhasil setup 3 VLAN di Linux + iptables antar-VLAN restriction.',
        kesalahanUmum: [{ masalah: '❌ VLAN tidak UP', solusi: 'Cek dengan `ip link show` — status harus UP. Kalau DOWN cek `dmesg` untuk error kernel.' }],
      },
      {
        nama: 'Metode 2: Linux Hardening dengan CIS Benchmarks (Menengah)',
        level: 'menengah',
        deskripsi: 'CIS Benchmarks = standar hardening Linux dari Center Internet Security. Ada tool otomatis untuk apply.',
        prasyarat: ['Linux Ubuntu/CentOS', 'Backup konfigurasi sebelum apply hardening'],
        langkah: [
          { judul: 'Backup konfigurasi', aksi: 'Sebelum hardening, backup penting: `sudo tar -czf ~/etc-backup.tar.gz /etc`. Dan buat user backup dengan sudo: `sudo useradd -m backupadmin && sudo usermod -aG sudo backupadmin`. Kalau ada masalah, bisa login via backupadmin.', command: 'sudo tar -czf ~/etc-backup.tar.gz /etc', expected: 'Backup user + config ada.' },
          { judul: 'Install Lynis untuk audit security', aksi: 'Install Lynis (security audit tool): `sudo apt install lynis -y`. Jalankan audit: `sudo lynis audit system`. Akan cek 200+ security checks —SSH, password, file permissions, kernel params, dll. Output index Hardening Index (skor 0-100).', command: 'sudo apt install lynis -y\nsudo lynis audit system', expected: 'Hardening Index skore (mis: 60/100).' },
          { judul: 'Hardening SSH (kritis)', aksi: 'Disable root SSH login: edit `/etc/ssh/sshd_config`, set `PermitRootLogin no`. Disable password auth (pakai key): `PasswordAuthentication no`. Restart: `sudo systemctl restart sshd`.', command: 'sudo systemctl restart sshd\nsudo grep PermitRootLogin /etc/ssh/sshd_config', expected: 'PermitRootLogin no.' },
          { judul: 'Disable services tidak perlu', aksi: 'List services jalan: `systemctl list-units --type=service --state=running`. Disable yang tidak perlu: `sudo systemctl disable --now cups` (printing) `sudo systemctl disable --now avahi-daemon` (mDNS) dsb.', command: 'systemctl list-units --type=service --state=running', expected: 'Services minimum identified.' },
          { judul: 'Setup auto security update', aksi: 'Ubuntu: `sudo apt install unattended-upgrades -y && sudo dpkg-reconfigure -plow unattended-upgrades`. CentOS/RHEL: `sudo yum install yum-cron -y && sudo systemctl enable yum-cron`.', command: 'sudo apt install unattended-upgrades -y', expected: 'Auto-update configured.' },
        ],
        outputAkhir: 'Berhasil hardening Linux dasar. Hardening Index naik dari ~60 ke 80+.',
        kesalahanUmum: [{ masalah: '❌ Hardening malah bunuh akses', solusi: 'Backup pakai backupadmin. Jangan disable SSH / network services langsung.' }],
      },
    ],
    mitigasi: 'Defense in depth & Zero Trust:\n\n**Zero Trust**: setiap akses harus diverifikasi, tidak ada trust berdasarkan network location.\n\n**Least privilege**: tiap user/service hanya punya akses minimum yang diperlukan.\n\n**MFA everywhere**: untuk akses admin/SSH/VPN, wajib MFA.',
  } as MateriData,
  // ============================ WAF SETUP ============================
  {
    judul: '🛡️ Web Application Firewall (WAF) Setup — ModSecurity + OWASP CRS',
    emoji: '🛡️',
    deskripsi: 'Pelajari setup ModSecurity WAF dengan OWASP Core Rule Set di Apache/Nginx untuk block SQLi, XSS, dan request berbahaya secara otomatis.',
    level: 'menengah',
    harga: 20000,
    hargaCoret: 30000,
    isGratis: false,
    tipe: 'pertahanan',
    tujuan: 'Kamu paham konsep WAF sebagai lapisan pertahanan aplikasi, mampu install ModSecurity dengan OWASP CRS, dan dapat tune rules untuk false positive minimal.',
    analogy: 'Bayangkan toko dengan satpam di depan. Satpam cek tas semua orang yang masuk, larang bawa senjata tajam. ModSecurity = satpam untuk aplikasi web — cek semua HTTP request, tolak yang terlihat berbahaya.',
    apaItu: 'Web Application Firewall (WAF) adalah proxy/filter di depan aplikasi web yang menganalisis HTTP request sebelum sampai ke backend. ModSecurity adalah WAF open source paling terkenal, OWASP CRS adalah ruleset standar yang digunakan industri.\n\nWAF defend dari: SQLi, XSS, RCE, RFI/LFI, scanner bots, dst.',
    senjata: { pc: '**ModSecurity** v2 atau v3 + **OWASP CRS**. Apache atau Nginx web server. Untuk lab lokal: install di laptop.', hp: 'Tidak praktis (setupnya butuh web server).' },
    metode: [
      {
        nama: 'Metode 1: Install ModSecurity di Apache (Pemula)',
        level: 'pemula',
        deskripsi: 'Cara paling straightforward: ModSecurity as Apache module. Setelah install, OWASP CRS aktif otomatis dengan rules default.',
        prasyarat: ['Apache web server', 'Sudo access'],
        langkah: [
          { judul: 'Install Apache', aksi: 'Kalian install Apache: `sudo apt install apache2 -y && sudo systemctl enable apache2 && sudo systemctl start apache2`. Test: akses `http://localhost`. Halaman default Apache tampil.', command: 'sudo apt install apache2 -y\nsudo systemctl enable apache2\nsudo systemctl start apache2', expected: 'Apache jalan.' },
          { judul: 'Install ModSecurity + dependencies', aksi: 'Install ModSecurity: `sudo apt install libapache2-mod-security2 -y`. Module aktif otomatis.', command: 'sudo apt install libapache2-mod-security2 -y', expected: 'ModSecurity installed.' },
          { judul: 'Aktifkan recommended config', aksi: 'Aktifkan config recommended: `sudo cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf`. Edit: `sudo nano /etc/modsecurity/modsecurity.conf`. Ubah `SecRuleEngine DetectionOnly` jadi `SecRuleEngine On` (kalau DetectionOnly, cuma log, tidak block).', command: 'sudo nano /etc/modsecurity/modsecurity.conf', expected: 'SecRuleEngine On.' },
          { judul: 'Download OWASP CRS', aksi: 'Download OWASP CRS 4.x (latest stable): `cd /tmp && wget https://github.com/coreruleset/coreruleset/releases/download/v4.0.0/coreruleset-4.0.0-minimal.tar.gz && tar -xzf coreruleset-4.0.0-minimal.tar.gz && sudo mv coreruleset-4.0.0 /etc/modsecurity/coreruleset`.', command: 'cd /tmp && wget https://github.com/coreruleset/coreruleset/releases/download/v4.0.0/coreruleset-4.0.0-minimal.tar.gz\ntar -xzf coreruleset-4.0.0-minimal.tar.gz\nsudo mv coreruleset-4.0.0 /etc/modsecurity/coreruleset', expected: 'CRS downloaded.' },
          { judul: 'Include CRS di ModSecurity config', aksi: 'Edit security2.conf: `sudo nano /etc/apache2/mods-enabled/security2.conf`. Tambah baris: `IncludeOptional /etc/modsecurity/coreruleset/crs-setup.conf` dan `IncludeOptional /etc/modsecurity/coreruleset/rules/*.conf` di akhir.', command: 'sudo nano /etc/apache2/mods-enabled/security2.conf', expected: 'CRS included.' },
          { judul: 'Restart Apache + test attack', aksi: 'Restart: `sudo systemctl restart apache2`. Tes detection: `curl "http://localhost/?id=1%20OR%201=1"`. Cek log: `sudo tail -f /var/log/apache2/modsec_audit.log`. Akan ada entry SQLi blocked.', command: 'sudo systemctl restart apache2\ncurl "http://localhost/?id=1%20OR%201=1"\nsudo tail -f /var/log/apache2/modsec_audit.log', expected: 'ModSecurity block SQLi request. Log entry muncul.' },
        ],
        outputAkhir: 'Berhasil install ModSecurity + OWASP CRS. Tes menunjukkan SQLi diblock otomatis.',
        kesalahanUmum: [{ masalah: '❌ False positive banyak', solusi: 'Run untuk 1-2 minggu dalam DetectionOnly mode dulu. Analyze log. Whitelist rule yang sering false-positive: `SecRuleUpdateActionById 942100 "pass"` di custom rules.' }],
      },
      {
        nama: 'Metode 2: Setup ModSecurity di Nginx (Menengah)',
        level: 'menengah',
        deskripsi: 'ModSecurity v3 sekarang support Nginx via module nginx-mod-security. Lebih scalable untuk high-traffic.',
        prasyarat: ['Nginx terinstall', 'Sudo access'],
        langkah: [
          { judul: 'Install dependencies', aksi: 'Kalian install build deps: `sudo apt install git build-essential libpcre3-dev libssl-dev libxml2-dev libyajl-dev libgeoip-dev -y`.', command: 'sudo apt install git build-essential libpcre3-dev libssl-dev libxml2-dev libyajl-dev libgeoip-dev -y', expected: 'Build deps installed.' },
          { judul: 'Clone ModSecurity + Nginx connector', aksi: 'Clone: `cd /opt && git clone https://github.com/owasp-modsecurity/ModSecurity && cd ModSecurity && git submodule init && git submodule update && ./build.sh && ./configure && make && sudo make install`.', command: 'cd /opt\ngit clone https://github.com/owasp-modsecurity/ModSecurity\ncd ModSecurity && git submodule init && git submodule update\n./build.sh && ./configure && make && sudo make install', expected: 'ModSecurity v3 compiled.' },
          { judul: 'Compile Nginx dengan ModSecurity connector', aksi: 'Lama dan kompleks. Alternatif yang lebih cepat: pakai ModSecurity-Nginx connector yang pre-built atau pakai distribusi Nginx dengan ModSecurity sudah included (misal: nginx-extras di Debian/Ubuntu).', expected: 'Nginx dengan ModSecurity ready.' },
          { judul: 'Konfigurasi ModSecurity untuk Nginx', aksi: 'Setup mirip Apache: aktifkan SecRuleEngine On, Include CRS rules. Letakkan di `/etc/nginx/modsec/main.conf` dan include di nginx.conf via `modsecurity on; modsecurity_rules_file /etc/nginx/modsec/main.conf;`.', expected: 'ModSecurity configured.' },
        ],
        outputAkhir: 'Berhasil setup ModSecurity di Nginx. Lebih scalable untuk production.',
        kesalahanUmum: [{ masalah: '❌ Compile error', solusi: 'Install semua build deps. Kalau masih error, pakai Docker image ModSecurity-Nginx yang pre-built.' }],
      },
    ],
    mitigasi: 'Layered defense:\n\n**WAF + Secure Coding**: WAF bukan pengganti secure coding. Keduanya saling melengkapi.\n\n**Managed WAF**: untuk yang tidak mau manage sendiri: Cloudflare WAF, AWS WAF, Azure WAF — managed service.\n\n**Rate limiting**: tambahkan rule WAF untuk limit request per IP.',
  } as MateriData,
  // ============================ WIFI SECURITY HARDENING ============================
  {
    judul: '📶 WiFi Security Hardening (WPA3, 802.1X, RADIUS)',
    emoji: '📶',
    deskripsi: 'Pelajari cara Meningkatkan keamanan WiFi: setup WPA3, setup server RADIUS untuk 802.1X enterprise-grade, dan monitoring WiFi.',
    level: 'sulit',
    harga: 25000,
    hargaCoret: 35000,
    isGratis: false,
    tipe: 'pertahanan',
    tujuan: 'Kamu paham WPA3 vs WPA2 beda teknis, mampu setup RADIUS server untuk 802.1X authentication, dan bisa memonitoring WiFi untuk rogue AP.',
    analogy: 'Bayangkan rumah. WPA2 = kunci standar yang bisa dipalsukan oleh pencuri ahli. WPA3 = kunci smart-lock dengan encryption dinamis yang tidak bisa dipalsukan. RADIUS = kunci yang hanya diberikan ke penghuni terdaftar setelah verifikasi data diri.',
    alat: 'Router/AP bisnis (Ubiquiti UniFi, MikroTik, Aruba, Cisco Meraki) untuk WPA3. Server FreeRADIUS untuk 802.1X. Kali Linux / Wireshark untuk monitoring.',
    senjata: { pc: '**FreeRADIUS** (server authentication), **hostapd** (AP mode Linux), **wpa_supplicant** (client 802.1X). Router modern support WPA3.', hp: 'HP tidak bisa jadi AP security grade. Tp-Link Deco / Google Nest support WPA3 di rumah.' },
    metode: [
      {
        nama: 'Metode 1: Setup WPA3 di Router Modern (Pemula)',
        level: 'pemula',
        deskripsi: 'Cara paling sederhana: aktifkan WPA3 di router WiFi modern (TP-Link, Asus, Ubiquiti, dsb).',
        prasyarat: ['Router support WPA3 (2019+)', 'Akses admin web router'],
        langkah: [
          { judul: 'Cek support WPA3 di router', aksi: 'Kalian buka halaman admin router (umumnya 192.168.1.1 atau 192.168.0.1). Login dengan admin password. Di wireless settings cari "Security Mode" atau "Encryption". Pilih opsi dengan "WPA3" — sering ada "WPA2/WPA3 Mixed" untuk backward compatibility.', expected: 'WPA3 option visible.' },
          { judul: 'Set password kuat (>16 karakter)', aksi: 'Set WiFi passphrase minimal 16 karakter random (misal: `kuda-bersepeda-mawar-rumah`). Jangan pakai kata yang ada di kamus, nama, tanggal lahir. Pakai password manager untuk generate random.', expected: 'Strong passphrase set.' },
          { judul: 'Disable WPS kalau tidak dipakai', aksi: 'WPS (WiFi Protected Setup) = password cracking surface. Disable di advanced wireless settings.', expected: 'WPS disabled.' },
          { judul: 'Disable SSID broadcast (opsional, sedit)', aksi: 'Hide SSID membuat WiFi tidak terlihat di scan — tapi masih bisa dideteksi lewat probe request. Tetap set sebagai fallback defense.', expected: 'SSID hidden.' },
        ],
        outputAkhir: 'Router WiFi sudah menggunakan WPA3 dengan password kuat.',
        kesalahanUmum: [{ masalah: '❌ Device lama tidak terkoneksi', solusi: 'Gunakan WPA2/WPA3 Mixed mode untuk backward compat. Atau ganti device lama yang tidak support WPA3.' }],
      },
      {
        nama: 'Metode 2: Setup FreeRADIUS untuk 802.1X Enterprise (Menengah)',
        level: 'menengah',
        deskripsi: 'Untuk enterprise (kantor / kampus), setup RADIUS server. Setiap user punya credential sendiri-sendiri, bukan satu password bersama seluruh organisasi.',
        prasyarat: ['Server Linux (Ubuntu/CentOS)', 'Akses ke AP manageable', 'Network IP statis'],
        langkah: [
          { judul: 'Install FreeRADIUS', aksi: 'Kalian install: `sudo apt install freeradius freeradius-utils -y`. FreeRADIUS berjalan sebagai service.', command: 'sudo apt install freeradius freeradius-utils -y', expected: 'FreeRADIUS installed.' },
          { judul: 'Tambah user di /etc/freeradius/users', aksi: 'Edit: `sudo nano /etc/freeradius/users`. Tambah user di akhir:\n```\nuser1 Cleartext-Password := "password123"\nuser2 Cleartext-Password := "password456"\n```\nUntuk prod, pakai hash NT-Password atau PAP dengan permission ketat.', expected: 'Users added.' },
          { judul: 'Tambah client (AP) di clients.conf', aksi: 'Edit: `sudo nano /etc/freeradius/clients.conf`. Tambah di akhir:\n```\nclient AP_IP {\n  secret = shared_secret_123\n  shortname = AP-LAB\n}\n```\nSecret akan dipakai AP untuk authenticate ke RADIUS.', expected: 'AP client added.' },
          { judul: 'Setup AP untuk pakai RADIUS', aksi: 'Di admin web AP Anda (Ubiquiti / MikroTik / Aruba), setup:\n- Security: WPA2-Enterprise (atau WPA3-Enterprise)\n- RADIUS server: IP FreeRADIUS server\n- RADIUS port: 1812, 1813\n- Shared secret: yang Anda set di clients.conf', expected: 'AP configured for RADIUS.' },
          { judul: 'Tes connection', aksi: 'Dari HP client: konek ke SSID enterprise dengan user `user1` dan password `password123`. Cek log RADIUS: `sudo tail -f /var/log/freeradius/radius.log`. Seharusnya ada Access-Accept.', command: 'sudo tail -f /var/log/freeradius/radius.log', expected: 'Access-Accept log.' },
        ],
        outputAkhir: 'Berhasil setup FreeRADIUS + 802.1X. Setiap user punya credential sendiri, bukan shared password.',
        kesalahanUmum: [{ masalah: '❌ HP tidak terkoneksi', solusi: 'Cek firewall FreeRADIUS port 1812/1813 UDP open: `sudo ufw allow 1812/udp && sudo ufw allow 1813/udp`.' }],
      },
    ],
    mitigasi: 'Defense lain:\n\n**Monitor WiFi untuk rogue AP**: tools Kismet / Aruba AirWave detect AP tidak dikenal yang meniru SSID.\n\n**IDS untuk WiFi**: tools seperti `aircrack-ng` detect anomali (bukan preventif).',
  } as MateriData,
  // ============================ SECURE CODING PRACTICES ============================
  {
    judul: '🔒 Secure Coding Practices — Tulis Code Aman dari Awal',
    emoji: '🔒',
    deskripsi: 'Pelajari 10 secure coding rules paling penting (OWASP ASVS), parameterized query, dan penggunaan tools static analysis (Semgrep).',
    level: 'menengah',
    harga: 20000,
    hargaCoret: 30000,
    isGratis: false,
    tipe: 'pertahanan',
    tujuan: 'Kamu paham OWASP Secure Coding Practices, bisa implementasi parameterized query + output encoding per OWASP ASVS, dan tahu setup static analysis tools.',
    analogy: 'Bayangkan tukang bangunan. Tukang amatur akan bikin rumah yang roboh saat angin kencang. Tukang ahli tahu standar keamanan: paku baja tahan karat, kayu grade A, fondasi beton spesifik. Secure coding = aplikasi yang tahan banting terhadap attack sejakfrom-foundation.',
    apaItu: 'Secure coding adalah praktek menulis kode aplikasi yang aman dari attack umum (SQLi, XSS, dll). OWASP Secure Coding Practices adalah checklist standar industri.\n\nTop 10 secure coding rules (OWASP ASVS):\n1) Parameterized query (vs string concat)\n2) Output encoding (vs raw HTML output)\n3) Input validation\n4) Authentication kuat\n5) Cryptography yang aman (bukan MD5)\n6) Session management aman (HttpOnly, regenerate ID)\n7) Error handling yang tidak bocor info\n8) Logging yang aman (tidak log password)\n9) Prinsip least privilege\n10) Update dependencies',
    senjata: { pc: 'Static analysis: **Semgrep** (polyglot, modern), **Bandit** (Python), **SonarQube** (enterprise), **CodeQL** (GitHub). Dynamic: OWASP ZAP, Burp Suite Active Scanner.', hp: 'Tidak relevan.' },
    metode: [
      {
        nama: 'Metode 1: Parameterized Query - Anti SQLi (Pemula)',
        level: 'pemula',
        deskripsi: 'Cara paling penting secure coding: gunakan parameterized query di database access. Bahasa apapun punya librarynya.',
        prasyarat: ['Code editor (VS Code)', 'Setup database (SQLite / MySQL)'],
        langkah: [
          { judul: '❌ Vulnerable: string concatenation (JANGAN)', aksi: 'Kalian buka code editor, contoh di Node.js:\n```js\n// JANGAN! Vulnerable SQLi\napp.get("/user/:id", (req, res) => {\n  const sql = "SELECT * FROM users WHERE id = " + req.params.id;\n  db.query(sql, (err, rows) => res.json(rows));\n});\n```\nAttacker bisa kirim `/user/1 OR 1=1` atau `/user/1 UNION SELECT password FROM users` = SELURUH user terekspos.', expected: 'Code vulnerable terlihat.' },
          { judul: '✅ Aman: parameterized query', aksi: 'Refactor pakai placeholder `?` di query + pass value di array terpisah:\n```js\n// AMAN: Parameterized query\napp.get("/user/:id", (req, res) => {\n  const sql = "SELECT * FROM users WHERE id = ?";\n  db.query(sql, [req.params.id], (err, rows) => res.json(rows));\n});\n```\nLibrary akan escape input user otomatis. Attacker coba payload apapun tidak akan jalan.', expected: 'Code aman ditulis ulang.' },
          { judul: '✅ Untuk Python (SQLAlchemy)', aksi: '```python\n# AMAN: SQLAlchemy\nuser = db.session.query(User).filter(User.id == user_id).first()\n```Atau raw query:\n```python\ndb.session.execute("SELECT * FROM users WHERE id = :id", {"id": user_id})\n```', expected: 'Python aman.' },
          { judul: '✅ Untuk PHP (PDO)', aksi: '```php\n// AMAN: PDO prepared statement\n$stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");\n$stmt->execute([$_GET["id"]]);\n$row = $stmt->fetch();\n```', expected: 'PHP aman.' },
        ],
        outputAkhir: 'Paham parameterized query di Node.js, Python, PHP. Contoh code vulnerable vs aman.',
        kesalahanUmum: [{ masalah: '❌ Pakai template literal tapi lupa parameterize', solusi: 'Template literal di JS (`${var}`) BUKAN aman untuk SQL. Tetap harus pakai prepared statement / parameter binding.' }],
      },
      {
        nama: 'Metode 2: Output Encoding untuk Anti XSS (Menengah)',
        level: 'menengah',
        deskripsi: 'Setiap output ke HTML harus escape karakter berbahaya. Framework modern auto, tapi developer harus tahu kenapa.',
        prasyarat: ['Code editor', 'Sample HTML page'],
        langkah: [
          { judul: '❌ Vulnerable: raw HTML output', aksi: 'Di React JSX: pakai `dangerouslySetInnerHTML` JANGAN sembarangan. Contoh salah:\n```jsx\n// JANGAN\n<div dangerouslySetInnerHTML={{__html: user.bio}} />\n```\nKalau `user.bio` berisi `<script>alert(1)</script>` = XSS executed.', expected: 'Vulnerable code.' },
          { judul: '✅ Aman: React escape default', aksi: 'React auto-escape untuk teks biasa:\n```jsx\n// AMAN: React auto-escape\n<div>{user.bio}</div>\n```\nTextContent aman. JSX menutupi otomatis. Hanya gunakan `dangerouslySetInnerHTML` kalau Anda 100% yakin sudah di-sanitize use library seperti DOMPurify.', expected: 'React aman.' },
          { judul: '✅ Untuk PHP: htmlspecialchars', aksi: '```php\n// AMAN: htmlspecialchars dengan ENT_QUOTES\n<?php echo htmlspecialchars($user["bio"], ENT_QUOTES, "UTF-8"); ?>\n```\nKarakter `<`, `>`, `"`, `\'` otomatis di-encode.', expected: 'PHP aman.' },
          { judul: '✅ Sanitize rich text dengan DOMPurify', aksi: 'Untuk HTML rich text (user boleh embed link, format):\n```js\nimport DOMPurify from "dompurify";\nconst clean = DOMPurify.sanitize(user.bio);\n<div dangerouslySetInnerHTML={{__html: clean}} />\n```\nDOMPurify strip XSS otomatis, pertahankan tag aman.', expected: 'DOMPurify aman.' },
        ],
        outputAkhir: 'Paham output encoding di React, PHP, dan dengan DOMPurify.',
        kesalahanUmum: [{ masalah: '❌ Sanitize setelah parse HTML', solusi: 'Selalu sanitize SEBELUM output, bukan setelah. Jangan parse HTML manual (regex = bug).' }],
      },
      {
        nama: 'Metode 3: Static Analysis dengan Semgrep (Lanjut)',
        level: 'lanjut',
        deskripsi: 'Gunakan Semgrep otomatis scan codebase untuk pattern vulnerable (SQLi, XSS, hardcoded secrets, dll).',
        prasyarat: ['Python + pip', 'Source code lokal (misal repo Node.js atau Python)'],
        langkah: [
          { judul: 'Install Semgrep', aksi: 'Kalian install: `pip install semgrep`. Verifikasi: `semgrep --version`.', command: 'pip install semgrep\nsemgrep --version', expected: 'Semgrep installed.' },
          { judul: 'Run automated scan', aksi: 'Pindah ke folder project: `cd ~/my-project`. Run: `semgrep --config=auto`. Semgrep otomatis detect bahasa & run rules OWASP Top 10, security-audit, dll. Akan list findings + severity.', command: 'semgrep --config=auto', expected: 'Findings muncul (jika ada).' },
          { judul: 'Scan specific security patterns', aksi: 'Run rules OWASP Top 10: `semgrep --config=p/owasp-top-ten`. Atau khusus secrets: `semgrep --config=p/secrets`. Atau XSS: `semgrep --config=p/xss`.', command: 'semgrep --config=p/owasp-top-ten', expected: 'Specific findings.' },
          { judul: 'Fix critical findings', aksi: 'Untuk setiap finding:\n1) Cek apakah true positive / false positive\n2) Jika true positive, fix pakai pattern aman dari panduan (parameterized query, output encoding, etc)\n3) Add unit test untuk prevent regression\nRun scan di CI/CD (GitHub Actions) untuk otomatis detect sebelum merge.', expected: 'Findings fixed.' },
        ],
        outputAkhir: 'Berhasil setup Semgrep, scan codebase, fix findings.',
        kesalahanUmum: [{ masalah: '❌ Terlalu banyak false positive', solusi: 'Tune rules di `.semgrepignore` atau config custom. Run di CI dengan `--error` flag hanya untuk severity > error.' }],
      },
    ],
    mitigasi: 'Defense layers:\n\n**Code Review**: setiap perubahan code harus di-review peer.\n\n**CI/CD integration**: run Semgrep + tests otomatis di setiap PR.\n\n**Threat Modeling**: pikirkan attack vector di awal design (STRIDE).',
  } as MateriData,
];

export default pertahanan1;
